#! /bin/bash

tempdir=./pgptempdir
export GNUPGHOME=$tempdir

read -p "Enter Client Name: " client_name
read -p "Enter Provider Name: " provider_name

comment="${client_name}_${provider_name}"
pubkeyname="${comment}.pub.txt"
privkeyname="${comment}.priv.txt"

echo -e "Creating temporary keyring directory: ${tempdir}"
mkdir -p $tempdir
chmod 700 $tempdir
echo -e "Done\n"

echo -e "Generating pgp key..."
gpg --batch --gen-key <<EOF
%no-protection
Key-Type: RSA
Key-Length: 4096
Name-Real: CreativePlanning
Name-Comment: ${comment}
Name-Email: support@creativeplanning.com
Expire-Date: 0
%commit
EOF
echo -e "Done\n"

echo -e "Exporting keys..."
gpg --batch --armor --export $comment > $pubkeyname
gpg --batch --armor --export-secret-keys $comment > $privkeyname
echo -e "Done\n"

echo -e "Keys were extracted to ${pubkeyname} and ${privkeyname}"
